name: Delete old workflow runs

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@c1a2f0de3fa4134a2357de83c92acff6e298bb8a
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: 'watch-versions.yml'
          retain_days: 1
          keep_minimum_runs: 25