name: Generate Client

on:
  push:
    branches:
      - ci-test # TODO: Replace with master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      # Setup: Creates a settings.xml (Without relying on Environment Variables)
      - name: Generate settings.xml
        run: |
          earthly +ci-generate-settings \
              --MAVEN_REPOSITORY_ID=github \
              --MAVEN_REPOSITORY_USER=${{ github.actor }} \
              --MAVEN_REPOSITORY_PASS=${{ github.token }}

      # Setup: Installs earthly
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -q -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Earthly version
        run: earthly --version

      - name: Build
        run: earthly +swagger-compile

      # TODO: Should only run on release
      - name: Push to Maven Repository
        run: |
          earthly +swagger-deploy \
            --MAVEN_REPOSITORY_ID=github \
            --MAVEN_REPOSITORY_URL=$MAVEN_REPO
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_REPO: https://maven.pkg.github.com/${{ github.repository }}
