name: Generate Client

on:
  push:
    branches:
      - ci-test # TODO: Replace with master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      # Setup: Creates a settings.xml (As a side effect, also installs maven)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          # Needs to be the same as MAVEN_REPOSITORY_ID below
          server-id: github
          java-version: '11'
          distribution: 'temurin'
          # Required, as earthly needs to copy the settings.xml
          settings-path: ${{ github.workspace }}

      # Setup: Installs earthly
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget –-quiet https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Earthly version
        run: earthly --version

      - name: Build
        run: earthly +swagger-compile

      # TODO: Should only run on release
      - name: Push to Maven Repository
        run: |
          earthly +swagger-deploy \
            --MAVEN_REPOSITORY_ID=github \
            --MAVEN_REPOSITORY_URL=$MAVEN_REPO
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_REPO: https://maven.pkg.github.com/${{ github.repository }}
